# Segmentation masks are used to create a mock depth map.

# Input Input image should be 8UC3 / RGB8
sensor_msgs/Image input
---
# Has the same spatial dimensions as the input,
# Type as in image_encodings.hpp: TYPE_8UC1
# Type as in opencv: CV_8UC1
#   background		= 0
#   blue cone		= 1
#   yellow cone		= 2
#   large orange cone	= 3
#   orange cone		= 4
sensor_msgs/Image segmentation_mask