name: Who tests the tester
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo 'your code' > 'my laptop.html'
      - uses: actions/upload-artifact@v3
        with:
          path: 'my laptop.html'



