name: Who tests the tester
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get -y install docker
          sudo apt-get -y install python3
      - uses: actions/checkout@v3
      - run: |
          echo 'your code' > 'my laptop'
      - uses: actions/upload-artifact@v3
        path: 'my laptop'



